### ISSUE TITLE
The power resume doesn't work normal

### ISSUE THREAD

**Issue by Eryone** [NightHammer1000/Marlin_ThinkerSE#1]
Hi, 
I have found an issue with it: When the printer happened the power loss, the power resume.
Then I tried to resume the printing, it will home XY at first instead of heat nozzle and bed at first.
- It will cause the cold nozzle remove the prints off from the bed and print failed.
(The nozzle stop at the random point and because of the gravity of the earth, the nozzle will drop the filament out.
Then it will create the big blob to stick the nozzle with prints)
Greeting

**Comment by NightHammer1000** [comment]
Hi.

I never used Power Resume without the Hardware Detection of it. 
Will look into the SD Card Power Resume used in 2.0
But from what I read it is supposed to Heat Up first and then move.
Didnt even find a setting to change that.

Will try it out today myself. But I need to get my X Layer Shift Issues sorted out first.

**Comment by NightHammer1000** [comment]
Decided to turn SD Card Power Resume off in this Config.

I dont like the constant writing to SD Card on each layer.
Will burn out a SD Card real fast.

I'll leave this open if anyone else has Ideas or a fix for this one.

**Comment by Eryone** [comment]
Well, this seems reasonable. This function does affect the SD card. I will close this issue, but I think you can point this out in the readme (to prevent others from being confused about this).
